# This action will create a Pull Request to merge all changes on DEVELOP
# into the TEST branch. PR will be created as a draft
name: Create test branch PR

on:
  push:
    branches:
    - develop
  milestone:
    types: [created, edited]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: "develop"
        destination_branch: "test"
        pr_title: "Pulling ${{ github.ref }} into TEST"
        pr_body: ":crown: *An automated PR*  This PR will pull all recent merges from DEVELOP into TEST"
        pr_label: "auto-pr from dev to test"
        pr_draft: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
  zap_scan:
    runs-on: ubuntu-latest
    name: Zap Scan EPIC Admin
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.3.0
        continue-on-error: true
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://eagle-dev.pathfinder.gov.bc.ca/admin'
          rules_file_name: '.zap/rules.tsv'
